### PR TITLE
Service node close hold up before endpoints deattach 

### LINKED ISSUE #53: Service node is restarted before device nodes
All nodes in NodeRED are restarted asynchronously and service node might be reinitialized before device nodes complete their closing procedure (a.k.a. race condition). Currently it's not a big deal, but in the future it might introduce bugs or crashes. Two things have to reassured:
* Service node starts closing only when all it's device nodes are done closing.
* Device nodes starts initializing only after service node finished initializing.

### PR DESCRIPTION
**Pull request by mrNedas**
* serviceNode variable add
Resolves #53

### CODE REVIEW

File: v1/sensor3700.js [hunk 1]
```diff
@@ -180,12 +181,13 @@ module.exports = function (RED) {
...
 
-      Promise.all(cancelObservationPromises).then(() => {
-        done();
-      }).catch((err) => {
+      Promise.all(cancelObservationPromises).catch((err) => {
         node.error(err);
-        done();
-      });
+      })
+        .finally(() => {
```
Comment (GiedriusM) [inline v1/sensor3700.js]: Lygiavimas?

File: v1/lesley-service.js [hunk 2]
```diff
@@ -46,22 +49,42 @@ module.exports = function (RED) {
...
-      this.service.stop().then(() => {
-        done();
-      }).catch((err) => {
-        this.error(err);
-        done();
+    serviceNode.attach = function (node) {
+      serviceNode.sensorNodes[node.id] = node;
+    };
+
+    serviceNode.deattach = function (node) {
```
Comment (GiedriusM) [inline v1/lesley-service.js]: Correct spelling is **detach**.
